//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Bill {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Bill.BillServicersSoap")]
    public interface BillServicersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnCheckBillIDByTableID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetUnCheckBillIDByTableID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnCheckBillIDByTableID", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetUnCheckBillIDByTableIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertBill(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBill", ReplyAction="*")]
        System.Threading.Tasks.Task InsertBillAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxBillID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetMaxBillID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxBillID", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetMaxBillIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void CheckOut(int billID, int discount, int totalPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckOut", ReplyAction="*")]
        System.Threading.Tasks.Task CheckOutAsync(int billID, int discount, int totalPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListBillByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetListBillByDate(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListBillByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetListBillByDateAsync(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteBill(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBill", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteBillAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BillServicersSoapChannel : GUI.Bill.BillServicersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServicersSoapClient : System.ServiceModel.ClientBase<GUI.Bill.BillServicersSoap>, GUI.Bill.BillServicersSoap {
        
        public BillServicersSoapClient() {
        }
        
        public BillServicersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServicersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServicersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServicersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetUnCheckBillIDByTableID(int id) {
            return base.Channel.GetUnCheckBillIDByTableID(id);
        }
        
        public System.Threading.Tasks.Task<int> GetUnCheckBillIDByTableIDAsync(int id) {
            return base.Channel.GetUnCheckBillIDByTableIDAsync(id);
        }
        
        public void InsertBill(int tableID) {
            base.Channel.InsertBill(tableID);
        }
        
        public System.Threading.Tasks.Task InsertBillAsync(int tableID) {
            return base.Channel.InsertBillAsync(tableID);
        }
        
        public int GetMaxBillID() {
            return base.Channel.GetMaxBillID();
        }
        
        public System.Threading.Tasks.Task<int> GetMaxBillIDAsync() {
            return base.Channel.GetMaxBillIDAsync();
        }
        
        public void CheckOut(int billID, int discount, int totalPrice) {
            base.Channel.CheckOut(billID, discount, totalPrice);
        }
        
        public System.Threading.Tasks.Task CheckOutAsync(int billID, int discount, int totalPrice) {
            return base.Channel.CheckOutAsync(billID, discount, totalPrice);
        }
        
        public System.Data.DataTable GetListBillByDate(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetListBillByDate(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetListBillByDateAsync(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetListBillByDateAsync(fromDate, toDate);
        }
        
        public bool DeleteBill(int id) {
            return base.Channel.DeleteBill(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBillAsync(int id) {
            return base.Channel.DeleteBillAsync(id);
        }
    }
}
